name: nextcloud_cookbook_flutter
description: A flutter client for the Nextcloud CookBook app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.9+24

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_translate:
    git:
      url: https://github.com/cornerman/flutter_translate.git
      ref: fallback-missing-strings

  # For DNS punycode translation
  punycode: ^1.0.0

  #for app key
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # For HTTP Requests
  http: ^0.13.1

  # flutter_bloc for simpler bloc implementation
  flutter_bloc: ^8.1.1

  # For easier handling without hand built hash comparison
  equatable: ^2.0.0

  # Search Field (For Category & Tags)
  searchfield: ^0.7.2

  # Search
  search_page: ^2.0.0

  # Settings Page
  flutter_settings_screens: ^0.3.3-null-safety+2

  theme_mode_handler: ^3.0.0

  # Form data HTTP Client
  dio: ^5.0.0

  # Screen always on
  wakelock: ^0.6.1

  xml: ^6.1.0

  flutter_spinkit: ^5.0.0
  validators: ^3.0.0

  flutter_svg: ^2.0.4

  flutter_markdown: ^0.6.9

  # Timer for cooking time
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: 2.0.0
  timezone: ^0.9.1

  cached_network_image: ^3.0.0
  #flutter_cache_manager: ^3.3.0
  flutter_cache_manager_dio:
    git:
      url: https://github.com/josh-burton/flutter_cache_manager_dio.git
      ref: dio-5.x
  dio_cache_interceptor_sembast_storage: ^0.1.0
  dio_cache_interceptor: ^3.4.1
  path_provider: ^2.0.14

  flutter_typeahead: ^4.3.7

  json_annotation: ^4.8.0

  nc_cookbook_api:
    git:
      url: https://github.com/Leptopoda/nextcloud_cookbook_dart_api.git
      ref: 5465b2fd64fb71cb7cd588989d1709fd48884457

  built_collection: ^5.1.1
  intl: ^0.18.0

  sliver_tools: ^0.2.8
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_launcher_icons: ^0.12.0

  json_serializable: ^6.6.0
  build_runner: ^2.3.0

  flutter_test:
    sdk: flutter

  lint: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icon.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
